//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        public int maphong { get; set; }
        public string tenphong { get; set; }
        public int NhanVien_manhanvien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
