//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720Trọng_63135896.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SINH_VIEN
    {
        [Display(Name = "Mã sinh viên")]
        public string Ma_sv { get; set; }

        [Display(Name = "Họ sinh viên")]
        public string Ho_sv { get; set; }

        [Display(Name = "Tên sinh viên")]
        public string Ten_sv { get; set; }

        [Display(Name = "Ngày sinh")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Ngay_sinh { get; set; }
        //public System.DateTime Ngay_sinh { get; set; }

        [Display(Name = "Giới tính")]
        public Nullable<bool> Gioi_tinh { get; set; }

        [Display(Name = "Ảnh sinh viên")]
        public string Anh_sv { get; set; }

        [Display(Name = "Địa chỉ")]
        public string Dia_chi { get; set; }

        [Display(Name = "Mã lớp")]
        public string Ma_lop { get; set; }

        public virtual LOP LOP { get; set; }
    }
}
